name: CI on PullRequest
on:
  pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Init projet
        uses: actions/checkout@v2
      - name: Use Node 17.7.2
        uses: actions/setup-node@v1
        with:
          node-version: '17.7.2'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
      - name: Test
        run: npm run test:ci
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_coverage
          path: coverage
